const MAIN_CURRENCY = [
  {
    code: 'USD',
    symbol: '$',
    bgPositionX: '-19.32145em',
    bgPositionY: '-3.25em',
    name: 'dolar',
    priority: 1,
  },
  {
    code: 'EUR',
    symbol: '€',
    bgPositionX: '-31.10718em',
    bgPositionY: '-3.25em',
    name: 'euro',
    priority: 2,
  },
  {
    code: 'GBP',
    symbol: '£',
    bgPositionX: '-17.17859em',
    bgPositionY: '-3.25em',
    name: 'funt brytyjski',
    priority: 3,
  },
  {
    code: 'CHF',
    symbol: '₣',
    bgPositionX: '-65.39294em',
    bgPositionY: '-2.17857em',
    name: 'frank',
    priority: 4,
  },
  {
    code: 'CNY',
    symbol: '¥',
    bgPositionX: '-42.89291em',
    bgPositionY: '-0.03571em',
    name: 'juan',
    priority: 5,
  },
  {
    code: 'TRY',
    symbol: '₺',
    bgPositionX: '-8.60715em',
    bgPositionY: '-3.25em',
    name: 'lira',
    priority: 6,
  },
  {
    code: 'CAD',
    symbol: '$',
    bgPositionX: '-36.46433em',
    bgPositionY: '-0.03571em',
    name: 'dolar kanadyjski',
    priority: 7,
  },
  {
    code: 'AUD',
    symbol: '$',
    bgPositionX: '-11.82144em',
    bgPositionY: '-0.03571em',
    name: 'dolar australijski',
    priority: 8,
  },
  {
    code: 'DKK',
    symbol: 'kr',
    bgPositionX: '-51.46435em',
    bgPositionY: '-0.03571em',
    name: 'Korona duńska',
    priority: 9,
  },
];

export default MAIN_CURRENCY;
