export const mockAllCurrencies = [
  { currency: 'bat (Tajlandia)', code: 'THB', mid: 0.1174 },
  { currency: 'dolar amerykański', code: 'USD', mid: 4.1191 },
  { currency: 'dolar australijski', code: 'AUD', mid: 2.7474 },
  { currency: 'dolar Hongkongu', code: 'HKD', mid: 0.527 },
  { currency: 'dolar kanadyjski', code: 'CAD', mid: 3.0981 },
  { currency: 'dolar nowozelandzki', code: 'NZD', mid: 2.5519 },
  { currency: 'dolar singapurski', code: 'SGD', mid: 3.0474 },
  { currency: 'euro', code: 'EUR', mid: 4.4754 },
  { currency: 'forint (Węgry)', code: 'HUF', mid: 0.011717 },
  { currency: 'frank szwajcarski', code: 'CHF', mid: 4.5894 },
  { currency: 'funt szterling', code: 'GBP', mid: 5.2362 },
  { currency: 'hrywna (Ukraina)', code: 'UAH', mid: 0.1115 },
  { currency: 'jen (Japonia)', code: 'JPY', mid: 0.028606 },
  { currency: 'korona czeska', code: 'CZK', mid: 0.1878 },
  { currency: 'korona duńska', code: 'DKK', mid: 0.6009 },
  { currency: 'korona islandzka', code: 'ISK', mid: 0.030137 },
  { currency: 'korona norweska', code: 'NOK', mid: 0.3849 },
  { currency: 'korona szwedzka', code: 'SEK', mid: 0.3759 },
  { currency: 'lej rumuński', code: 'RON', mid: 0.9037 },
  { currency: 'lew (Bułgaria)', code: 'BGN', mid: 2.2882 },
  { currency: 'lira turecka', code: 'TRY', mid: 0.1578 },
  { currency: 'nowy izraelski szekel', code: 'ILS', mid: 1.1114 },
  { currency: 'peso chilijskie', code: 'CLP', mid: 0.005168 },
  { currency: 'peso filipińskie', code: 'PHP', mid: 0.0741 },
  { currency: 'peso meksykańskie', code: 'MXN', mid: 0.2419 },
  { currency: 'rand (Republika Południowej Afryki)', code: 'ZAR', mid: 0.2183 },
  { currency: 'real (Brazylia)', code: 'BRL', mid: 0.8495 },
  { currency: 'ringgit (Malezja)', code: 'MYR', mid: 0.8834 },
  { currency: 'rupia indonezyjska', code: 'IDR', mid: 0.00027379 },
  { currency: 'rupia indyjska', code: 'INR', mid: 0.049909 },
  { currency: 'won południowokoreański', code: 'KRW', mid: 0.003162 },
  { currency: 'yuan renminbi (Chiny)', code: 'CNY', mid: 0.5686 },
  { currency: 'SDR (MFW)', code: 'XDR', mid: 5.4804 },
  { currency: 'afgani (Afganistan)', code: 'AFN', mid: 0.047165 },
  { currency: 'ariary (Madagaskar)', code: 'MGA', mid: 0.000898 },
  { currency: 'balboa (Panama)', code: 'PAB', mid: 4.0869 },
  { currency: 'birr etiopski', code: 'ETB', mid: 0.0743 },
  { currency: 'boliwar soberano (Wenezuela)', code: 'VES', mid: 0.1453 },
  { currency: 'boliwiano (Boliwia)', code: 'BOB', mid: 0.5894 },
  { currency: 'colon kostarykański', code: 'CRC', mid: 0.007532 },
  { currency: 'colon salwadorski', code: 'SVC', mid: 0.4669 },
  { currency: 'cordoba oro (Nikaragua)', code: 'NIO', mid: 0.1117 },
  { currency: 'dalasi (Gambia)', code: 'GMD', mid: 0.0652 },
  { currency: 'denar (Macedonia Północna)', code: 'MKD', mid: 0.072219 },
  { currency: 'dinar algierski', code: 'DZD', mid: 0.030103 },
  { currency: 'dinar bahrajski', code: 'BHD', mid: 10.8413 },
  { currency: 'dinar iracki', code: 'IQD', mid: 0.00312 },
  { currency: 'dinar jordański', code: 'JOD', mid: 5.7621 },
  { currency: 'dinar kuwejcki', code: 'KWD', mid: 13.3028 },
  { currency: 'dinar libijski', code: 'LYD', mid: 0.8501 },
  { currency: 'dinar serbski', code: 'RSD', mid: 0.0379 },
  { currency: 'dinar tunezyjski', code: 'TND', mid: 1.3176 },
  { currency: 'dirham marokański', code: 'MAD', mid: 0.4196 },
  {
    currency: 'dirham ZEA (Zjednoczone Emiraty Arabskie)',
    code: 'AED',
    mid: 1.1128,
  },
  {
    currency: 'dobra (Wyspy Świętego Tomasza i Książęca)',
    code: 'STN',
    mid: 0.1817,
  },
  { currency: 'dolar bahamski', code: 'BSD', mid: 4.0869 },
  { currency: 'dolar barbadoski', code: 'BBD', mid: 2.0243 },
  { currency: 'dolar belizeński', code: 'BZD', mid: 2.0278 },
  { currency: 'dolar brunejski', code: 'BND', mid: 3.023 },
  { currency: 'dolar Fidżi', code: 'FJD', mid: 1.8387 },
  { currency: 'dolar gujański', code: 'GYD', mid: 0.019325 },
  { currency: 'dolar jamajski', code: 'JMD', mid: 0.0266 },
  { currency: 'dolar liberyjski', code: 'LRD', mid: 0.0223 },
  { currency: 'dolar namibijski', code: 'NAD', mid: 0.2185 },
  { currency: 'dolar surinamski', code: 'SRD', mid: 0.1086 },
  { currency: 'dolar Trynidadu i Tobago', code: 'TTD', mid: 0.6028 },
  { currency: 'dolar wschodniokaraibski', code: 'XCD', mid: 1.5084 },
  { currency: 'dolar Wysp Salomona', code: 'SBD', mid: 0.4811 },
  { currency: 'dolar Zimbabwe', code: 'ZWL', mid: 0.000757 },
  { currency: 'dong (Wietnam)', code: 'VND', mid: 0.00017208 },
  { currency: 'dram (Armenia)', code: 'AMD', mid: 0.010562 },
  { currency: 'escudo Zielonego Przylądka', code: 'CVE', mid: 0.0402 },
  { currency: 'florin arubański', code: 'AWG', mid: 2.2582 },
  { currency: 'frank burundyjski', code: 'BIF', mid: 0.001446 },
  { currency: 'frank CFA BCEAO ', code: 'XOF', mid: 0.006781 },
  { currency: 'frank CFA BEAC', code: 'XAF', mid: 0.006698 },
  { currency: 'frank CFP  ', code: 'XPF', mid: 0.037276 },
  { currency: 'frank Dżibuti', code: 'DJF', mid: 0.022956 },
  { currency: 'frank gwinejski', code: 'GNF', mid: 0.000475 },
  { currency: 'frank Komorów', code: 'KMF', mid: 0.00905 },
  {
    currency: 'frank kongijski (Dem. Republika Konga)',
    code: 'CDF',
    mid: 0.001665,
  },
  { currency: 'frank rwandyjski', code: 'RWF', mid: 0.003519 },
  { currency: 'funt egipski', code: 'EGP', mid: 0.1323 },
  { currency: 'funt gibraltarski', code: 'GIP', mid: 5.1953 },
  { currency: 'funt libański', code: 'LBP', mid: 0.000272 },
  { currency: 'funt południowosudański', code: 'SSP', mid: 0.004129 },
  { currency: 'funt sudański', code: 'SDG', mid: 0.0068 },
  { currency: 'funt syryjski', code: 'SYP', mid: 0.0016 },
  { currency: 'Ghana cedi ', code: 'GHS', mid: 0.3601 },
  { currency: 'gourde (Haiti)', code: 'HTG', mid: 0.0293 },
  { currency: 'guarani (Paragwaj)', code: 'PYG', mid: 0.000563 },
  { currency: 'gulden Antyli Holenderskich', code: 'ANG', mid: 2.2679 },
  { currency: 'kina (Papua-Nowa Gwinea)', code: 'PGK', mid: 1.1289 },
  { currency: 'kip (Laos)', code: 'LAK', mid: 0.000214 },
  { currency: 'kwacha malawijska', code: 'MWK', mid: 0.00388 },
  { currency: 'kwacha zambijska', code: 'ZMW', mid: 0.2326 },
  { currency: 'kwanza (Angola)', code: 'AOA', mid: 0.0049 },
  { currency: 'kyat (Myanmar, Birma)', code: 'MMK', mid: 0.001946 },
  { currency: 'lari (Gruzja)', code: 'GEL', mid: 1.572 },
  { currency: 'lej Mołdawii', code: 'MDL', mid: 0.2232 },
  { currency: 'lek (Albania)', code: 'ALL', mid: 0.042641 },
  { currency: 'lempira (Honduras)', code: 'HNL', mid: 0.1661 },
  { currency: 'leone (Sierra Leone)', code: 'SLE', mid: 0.2044 },
  { currency: 'lilangeni (Eswatini)', code: 'SZL', mid: 0.2184 },
  { currency: 'loti (Lesotho)', code: 'LSL', mid: 0.2184 },
  { currency: 'manat azerbejdżański', code: 'AZN', mid: 2.4043 },
  { currency: 'metical (Mozambik)', code: 'MZN', mid: 0.0637 },
  { currency: 'naira (Nigeria)', code: 'NGN', mid: 0.005299 },
  { currency: 'nakfa (Erytrea)', code: 'ERN', mid: 0.2711 },
  { currency: 'nowy dolar tajwański', code: 'TWD', mid: 0.1313 },
  { currency: 'nowy manat (Turkmenistan)', code: 'TMT', mid: 1.1679 },
  { currency: 'ouguiya (Mauretania)', code: 'MRU', mid: 0.1183 },
  { currency: "pa'anga (Tonga)", code: 'TOP', mid: 1.7484 },
  { currency: 'pataca (Makau)', code: 'MOP', mid: 0.5062 },
  { currency: 'peso argentyńskie', code: 'ARS', mid: 0.0158 },
  { currency: 'peso dominikańskie', code: 'DOP', mid: 0.0737 },
  { currency: 'peso kolumbijskie', code: 'COP', mid: 0.000987 },
  { currency: 'peso kubańskie', code: 'CUP', mid: 4.0869 },
  { currency: 'peso urugwajskie', code: 'UYU', mid: 0.1092 },
  { currency: 'pula (Botswana)', code: 'BWP', mid: 0.3037 },
  { currency: 'quetzal (Gwatemala)', code: 'GTQ', mid: 0.5213 },
  { currency: 'rial irański', code: 'IRR', mid: 0.000097 },
  { currency: 'rial jemeński', code: 'YER', mid: 0.016334 },
  { currency: 'rial katarski', code: 'QAR', mid: 1.1216 },
  { currency: 'rial omański', code: 'OMR', mid: 10.6092 },
  { currency: 'rial saudyjski', code: 'SAR', mid: 1.0898 },
  { currency: 'riel (Kambodża)', code: 'KHR', mid: 0.00099 },
  { currency: 'rubel białoruski', code: 'BYN', mid: 1.2955 },
  { currency: 'rubel rosyjski', code: 'RUB', mid: 0.0454 },
  { currency: 'rupia lankijska', code: 'LKR', mid: 0.013292 },
  { currency: 'rupia (Malediwy)', code: 'MVR', mid: 0.2644 },
  { currency: 'rupia Mauritiusu', code: 'MUR', mid: 0.0898 },
  { currency: 'rupia nepalska', code: 'NPR', mid: 0.031087 },
  { currency: 'rupia pakistańska', code: 'PKR', mid: 0.0149 },
  { currency: 'rupia seszelska', code: 'SCR', mid: 0.3023 },
  { currency: 'sol (Peru)', code: 'PEN', mid: 1.126 },
  { currency: 'som (Kirgistan)', code: 'KGS', mid: 0.0468 },
  { currency: 'somoni (Tadżykistan)', code: 'TJS', mid: 0.3731 },
  { currency: 'sum (Uzbekistan)', code: 'UZS', mid: 0.000354 },
  { currency: 'szyling kenijski', code: 'KES', mid: 0.029029 },
  { currency: 'szyling somalijski', code: 'SOS', mid: 0.007177 },
  { currency: 'szyling tanzański', code: 'TZS', mid: 0.001685 },
  { currency: 'szyling ugandyjski', code: 'UGX', mid: 0.001107 },
  { currency: 'taka (Bangladesz)', code: 'BDT', mid: 0.037688 },
  { currency: 'tala (Samoa)', code: 'WST', mid: 1.511 },
  { currency: 'tenge (Kazachstan)', code: 'KZT', mid: 0.009219 },
  { currency: 'tugrik (Mongolia)', code: 'MNT', mid: 0.001185 },
  { currency: 'vatu (Vanuatu)', code: 'VUV', mid: 0.03414 },
  {
    currency: 'wymienialna marka (Bośnia i Hercegowina)',
    code: 'BAM',
    mid: 2.2702,
  },
  { currency: 'dolar amerykański', code: 'USD', bid: 4.0471, ask: 4.1289 },
  { currency: 'dolar australijski', code: 'AUD', bid: 2.6988, ask: 2.7534 },
  { currency: 'dolar kanadyjski', code: 'CAD', bid: 3.0507, ask: 3.1123 },
  { currency: 'euro', code: 'EUR', bid: 4.4081, ask: 4.4971 },
  { currency: 'forint (Węgry)', code: 'HUF', bid: 0.01165, ask: 0.011886 },
  { currency: 'frank szwajcarski', code: 'CHF', bid: 4.513, ask: 4.6042 },
  { currency: 'funt szterling', code: 'GBP', bid: 5.1518, ask: 5.2558 },
  { currency: 'jen (Japonia)', code: 'JPY', bid: 0.028069, ask: 0.028637 },
  { currency: 'korona czeska', code: 'CZK', bid: 0.1854, ask: 0.1892 },
  { currency: 'korona duńska', code: 'DKK', bid: 0.5918, ask: 0.6038 },
  { currency: 'korona norweska', code: 'NOK', bid: 0.3805, ask: 0.3881 },
  { currency: 'korona szwedzka', code: 'SEK', bid: 0.3727, ask: 0.3803 },
  { currency: 'SDR (MFW)', code: 'XDR', bid: 5.3958, ask: 5.5048 },
];

export const mainCurrencies = [
  {
    code: 'USD',
    symbol: '$',
    bgPositionX: '-19.32145em',
    bgPositionY: '-3.25em',
    name: 'dolar',
    mid: 4.1191,
    priority: 1,
  },
  {
    bgPositionX: '-11.82144em',
    bgPositionY: '-0.03571em',
    code: 'AUD',
    mid: 2.7474,
    name: 'dolar australijski',
    priority: 8,
    symbol: '$',
  },
];
